spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33068/payments_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: mysql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8080

jwt:
  issuer: "payments-be"
  secret-key: local-payments-key
  expiry-seconds: 10800000

springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    doc-expansion: none
  cache.disabled: true

toss:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace